### ISSUE TITLE
Installation yields "error: mierror: mixedSources(".../QuickOnLinuxExample/Packages/Nimble-3.1.1/Sources/Nimble")

### ISSUE THREAD

**Issue by geraldarthurdavis** [Quick/QuickOnLinuxExample#1]
After cloning the repo and running `swift build` I get the following output:

```
Cloning https://github.com/briancroom/Quick.git
HEAD is now at 8db5de5 Merge pull request #489 from takecian/issue457
Resolved version: 0.9.2
Cloning https://github.com/briancroom/Nimble
HEAD is now at dbcb07d Move test files and make adjustments to work with "swift test"
Resolved version: 3.1.1
error: mixedSources(".../QuickOnLinuxExample/Packages/Nimble-3.1.1/Sources/Nimble")
```

`$ swiftenv version`
`3.0 (set by /Users/.../.swiftenv/version)`

**Comment by DavidAntliff** [comment]
I think I'm getting the same problem on Ubuntu 14.04 but with slightly different output:

```
$ swift build
Cloning https://github.com/briancroom/Quick.git
HEAD is now at 8db5de5 Merge pull request #489 from takecian/issue457
Resolved version: 0.9.2
Cloning https://github.com/briancroom/Nimble
HEAD is now at dbcb07d Move test files and make adjustments to work with "swift test"
Resolved version: 3.1.1
error: the module at [...]Quick/QuickOnLinuxExample.git/Packages/Nimble-3.1.1/Sources/Nimble contains mixed language source files
fix: use only a single language within a module

$ swift --version
Swift version 3.0 (swift-3.0-PREVIEW-4)
Target: x86_64-unknown-linux-gnu
```

**Comment by modocache** [comment]
This might be due to changes in SwiftPM?

A great contribution here, to keep this example project working, would be to add a `.travis.yml` file we can use to confirm it all still works.

**Comment by pcantrell** [comment]
I’m getting this same error on macOS, Xcode 8 beta 6, so it’s not just Linux.

**Comment by tonyarnold** [comment]
I'm seeing this as well on macOS. I'll see what I can pull together for the `.travis.yml` - are there existing examples for SwiftPM on Linux that I can draw on?

**Comment by tonyarnold** [comment]
You can see the full error on TravisCI, running against my fork: https://travis-ci.org/tonyarnold/QuickOnLinuxExample

**Comment by tonyarnold** [comment]
So it seems that this particular error is not present in Quick v0.10.0 and Nimble v5.0.0. I've restructured the project a little in #2, and that seems to be working as expected (excepting the requirement of using `dependencies` vs the now-removed `testDependencies`).

**Comment by ikesyo** [comment]
Closing as this is so outdated.
